### ISSUE TITLE
what is rev2 

### ISSUE THREAD

**Issue by pashky** [omkbd/ErgoDash#1]
Hi,

I'm interested in implementing this design, but I'm curious what is rev2 mentioned in latest firmware change? Is PCB different from available in this repo?

**Comment by omkbd** [comment]
Sorry for replying so late.
Rev.2 in QMK is Rev.1 in this repo. Rev.1 in QMK is not available.

**Comment by pashky** [comment]
Hi 

Yeah, I’ve already built one and figured this out. Thanks for sharing all the docs and code, btw, I like using this keyboard very much!

**Comment by kumiDa** [comment]
> Sorry for replying so late. Rev.2 in QMK is Rev.1 in this repo. Rev.1 in QMK is not available.

This needs to be in the repo's README @omkbd, I will be happy to raise a patch for the same if you want me to.
