### ISSUE TITLE
Supported Stabilizers

### ISSUE THREAD

**Issue by christo-san** [omkbd/ErgoDash#10]
Hello,
Just having some issues with the build. 

1. I'm using [zeal stabs](https://zealpc.net/products/zealstabilizers) and I can't seem to place two of them on the thumb cluster. They seam to overlap just enough to not allow both to properly seat. Just wondering if anyone has has used these successfully in this orientation, or do I have to use the cherry stabs

2. Even after using just one zeal stab, the acrylic switch plate doesn't seem to sit well on it making it rather challenging to sit switches on the plate and into the pcb for soldering. 

Just curious if anyone else having these issues with the cherry stabs before I go out and order a few.

Thanks

**Comment by omkbd** [comment]
Sorry, I examined only this stabilizer.
https://kbdfans.cn/collections/keyboard-stabilizer/products/transparent-pcb-stabilizers-27
