### ISSUE TITLE
the documentation is extremely confusing!

### ISSUE THREAD

**Issue by rmarinbe** [omkbd/ErgoDash#12]
I have board revision 1.2 and I found the building documentation (English) very confusing and mixed with japanesse.
For example, there are two possible locations for the pro-micro, but it is not specified which side the pro-micro should be attached
for example, it says:

"but pay attention when installing the Pro Micro!!!!!! Note: The below diagrams are for rev 1.1. For rev 1.2. and up, the part placement is slightly different."

![image](https://user-images.githubusercontent.com/50396949/57356397-ed37ab80-71a2-11e9-9d87-46905c9f2654.png)

for the master and slave in the latest firmware ( after this date 2019/5/5): Do I need to do any soldering (jumper) as it is shown below or not?

![image](https://user-images.githubusercontent.com/50396949/57356831-0a20ae80-71a4-11e9-9f45-05b3a5e32970.png)

**Comment by omkbd** [comment]
I'm sorry I confused you.

"but pay attention when installing the Pro Micro!!!!!! Note: The below diagrams are for rev 1.1. For rev 1.2. and up, the part placement is slightly different."
>>Plaese read section 6.
https://github.com/omkbd/ErgoDash/blob/master/Doc/build-en.md#6-pro-micro-header--and-reset-switch-installation

for the master and slave in the latest firmware ( after this date 2019/5/5): Do I need to do any soldering (jumper) as it is shown below or not?
>>The latest version is as follows.
https://github.com/omkbd/picture/blob/master/Jump2-en.png
