### ISSUE TITLE
does ergodash support to use Ergodox EZ configurator

### ISSUE THREAD

**Issue by hpo14** [omkbd/ErgoDash#15]
as title.
[ErgoDox EZ Configurator](http://configure.ergodox-ez.com/ergodox-ez/layouts/default/latest/0)

**Comment by omkbd** [comment]
Not supported.
Please use qmk configurator.
https://config.qmk.fm/#/ergodash/rev1/LAYOUT

**Comment by hpo14** [comment]
OK, thanks
