### ISSUE TITLE
LEDs and inconsistant keys

### ISSUE THREAD

**Issue by nutimnot** [omkbd/ErgoDash#18]
Hello,

I built this board yesterday and have been having some issues. First I cannot figure out how to turn the LEDs on. I flashed my custom .hex file to the keyboard but other than that i cannot get the lights to turn on. I update the file like the instructions say but i'm not sure how they're supposed to populate to the board itself.

Secondly i've been having some issues getting keys to work sometimes. For example when i built the board, I couldn't get my 7 key to work, i thought I had soldered it incorrectly but everything else works. Now the 7 works fine and the enter key doesn't work without changing anything. Also sometimes the keys need to be pressed a few times before they'll register with the computer. Any assistance would be greatly appriciated, thank you!

**Comment by omkbd** [comment]
・First question
Press BL_TOGG or RGB_TOG.

・Second question
I can only think of checking the soldering.

**Comment by nutimnot** [comment]
Thanks for the reply! How do I press BL_TOGG or RGB_TOG?

EDIT: So i resoldered some of the misbehaving keys and they work great now. Now the only issue I have is with the LEDs. I set two different buttons on the keyboard, one as BL_TOGG and one as RGB_TOGG and neither of them do anything.

EDIT 2: now the entire HJKL: row isn't working on the right pad. It worked great last night and now I come into work and they don't do anything. Everything else works fine but I'm not sure why this would have changed just from bringing it into work, i was very gentle. Any help would be greatly appreciated.

**Comment by brethash** [comment]
@nutimnot could you post a couple pictures of the boards? It might help rule out soldering as the culprit.

**Comment by nutimnot** [comment]
@brethash here are some pictures. I got home just now and added some more solder to the mis-behaving keys and reflashed that side of the keyboard to no avail, the entire HJKL:" row is dead.

for reference, in the picture the middle row is the HJKL:" row
![IMG_20190524_162928](https://user-images.githubusercontent.com/50968099/58361320-840e9400-7e42-11e9-87bb-be9ab9587712.jpg)
![IMG_20190524_163000](https://user-images.githubusercontent.com/50968099/58361321-85d85780-7e42-11e9-98ea-61c9601bf68a.jpg)

**Comment by GreenShadowMaker** [comment]
I haven't had working RGB LEDs on either of the 2 I built.. I'm pretty sure I screwed up my first build.(backwards on one side) not sure why my second didn't work.

But, in your photos you haven't done the RGB jumper connetion.

**Comment by GreenShadowMaker** [comment]
For an entire row that stopped working, it may be the pro-micro connection.

**Comment by nutimnot** [comment]
@GreenShadowMaker how would i go about fixing that kind of issue?

EDIT: Follow up question, if it was working totally fine and then stopped, what would be the cause of that? I didn't do any soldering or anything and it stopped working, the row that is.

**Comment by nutimnot** [comment]
I managed to fix the issues with the HJKL row. One of the points on the Pro micro wasn't soldered well, so I remelted it and now it's fully functional (typed this reply on the keyboard). If anyone knows why the LEDs aren't working let me know. I don't have any resistors set up, the kit only came with diodes.

**Comment by brethash** [comment]
@nutimnot you won't need any additional resistors for the undermount LEDs to work. The resistors are only needed for the backlight/switch LEDs. 

If you're using the default keymap for the keyboard, try flashing @GreenShadowMaker 's keymap. It seems like his has the undermount LEDs on by default (at least thats what it seemed like when I flashed it anyway). The layers in his keymap are also a bit easier to work with in my opinion.

**Comment by nutimnot** [comment]
@brethash where can I find their keymap?

**Comment by brethash** [comment]
The keymap is [here](https://github.com/qmk/qmk_firmware/tree/master/keyboards/ergodash/rev1/keymaps/greenshadowmaker) and the layout itself is [here](https://github.com/qmk/qmk_firmware/blob/master/keyboards/ergodash/rev1/keymaps/greenshadowmaker/keymap.c). To toggle the `adjust` layer, the raise and lower keys are pressed at the same time (for me they were the keys directly below the `B` and the `N`.

**Comment by nutimnot** [comment]
Awesome thank you! Now I'd just try flashing it with QMK and see if it works yeah?

**Comment by brethash** [comment]
Yep! You should be able to build/flash it with `make ergodash/rev1:greenshadowmaker:avrdude` from the root of the `QMK` folder.

**Comment by nutimnot** [comment]
@brethash how do you do that using the QMK toolbox?

**Comment by brethash** [comment]
@nutimnot that's a good question! I've actually not used the QMK toolbox before; I always just build and flash from the command line, so I'm not sure how it works. 😞

**Comment by nutimnot** [comment]
I flashed it but it didn't turn on the LEDs so i'm not sure. Maybe I will try something else or test to see if the LEDs work at all I guess. Thank you @brethash for all your help my guy

**Comment by omkbd** [comment]
You haven't done the RGB jumper connetion.
You have to read this.
https://github.com/omkbd/ErgoDash/blob/master/Doc/build-en.md#5-underglow-led-optional

**Comment by nutimnot** [comment]
@omkbd So I just have to solder those two connections at the top of the board? I shouldn't need anything other than some solder, right? I don't have any resistors installed or anything. I'll try it out this week

**Comment by nutimnot** [comment]
I got it to work, thank you @omkbd and @brethash for y'alls help <3
