### ISSUE TITLE
Have you consider to support hotplug socket for switch ?

### ISSUE THREAD

**Issue by hpo14** [omkbd/ErgoDash#20]
just like ErgoDox's "Change It Youself" product, it use the hot plug socket to let user
can easily change switches.

![hotplug_socket](https://cdn.shopify.com/s/files/1/1152/3264/t/25/assets/neat-ciy-board.jpg?44054)

**Comment by omkbd** [comment]
It is under development.
Look at my twitter.
https://twitter.com/omkbd
