### ISSUE TITLE
Plans to add revision 1.3 or 2.0 PCB schematics and spec?

### ISSUE THREAD

**Issue by richerve** [omkbd/ErgoDash#27]
I've seen in your twitter account @omkbd pictures of PCBs version 1.3 and 2.0, this last one with hot-swappable switches and what it looks like a usb-c interconnect between the two sides. Do you have any plan on releasing the source for those revisions or are just private iterations not ready to be shared?

**Comment by richerve** [comment]
Ping @omkbd

**Comment by JimmyMultani** [comment]
Hey @omkbd, any plans to release these schematics? Thank you.

**Comment by MattBlissett** [comment]
I'd like to make an Ergodash.  Are the two changes above (hot-swappable switches, USB-C) and the rotary encoder (from the other issue and Twitter) the changes expected in r1.3 / r2.0, or is there more?

**Comment by lucasfperotti** [comment]
@omkbd Oh my god yes !!! I was about to buy a corne kbd kit just because i could not find a ergo dash with hot swap mx switches but if a 2.0 is going to happen i will get that !!! I am a great fan of this keyboard !

**Comment by MattBlissett** [comment]
I just finished making my hot-swap Ergodash (rev 1.2). I used [Mill-Max sockets](https://www.mouser.com/ProductDetail/mill-max/0305-2-15-80-47-80-10-0/), as in [this build](https://www.reddit.com/r/MechanicalKeyboards/comments/bvm3pe/my_first_build_ergodash_with_hotswappable/) ([more detail](https://www.reddit.com/r/MechanicalKeyboards/comments/bvm6zf/my_first_build_ergodash_with_hotswappable/)).

I'm glad I used the slightly longer 0305 sockets, it was less fiddly than I expected. However, the socket for the key above the Pro Micro touches one of the Pro Micro's capacitors, so it's about 0.7mm higher than it should be. 

I'm not sure what Falba Tech use, as they sell the Ergodash preassembled with Mill-Max sockets.

**Comment by Geobert** [comment]
What I'm super hype on this 2.0 is the 4 keys thumb cluster, so I really hope 2.0 will become a thing!

**Comment by richerve** [comment]
@omkbd any update on this?

**Comment by omkbd** [comment]
I am very busy now. I will be able to resume development in a little more time.

**Comment by n8gray** [comment]
Thanks for the update- count me in with the others who would be thrilled by a socketed design.

**Comment by NellyWhads** [comment]
Hey @omkbd any chance this is coming soon? If you need help, I'm more than happy to pitch in any way I can. Dying to get a v2.0 (at least from the teaser pics)

**Comment by MMMikeM** [comment]
@omkbd is the project still active?

**Comment by richerve** [comment]
As this was mainly a question and haven't been answered in more than a year, will close it.
