### ISSUE TITLE
MJ-4PP-9 TRRS jack not available in europe

### ISSUE THREAD

**Issue by derwana** [omkbd/ErgoDash#35]
MJ-4PP-9 TRRS jack seems not to be available nor shippable (without orbitant shippingcosts) to europe. Does anyone got an alternative? Else i'd fork the repo to implement an other jack.

**Comment by strayer** [comment]
I also couldn't find the TRRS jacks anywhere in Europe. In the end I ordered them on AliExpress: https://de.aliexpress.com/item/32874772300.html

**Comment by derwana** [comment]
I am doing a new footprint of a part available on mouser and farnell right now. Maybe doing a pullrequest later with an updated DOM on Octopart.
