### ISSUE TITLE
parts says 66-70 keys, couldn't you use 72?

### ISSUE THREAD

**Issue by jack-faller** [omkbd/ErgoDash#41]
the parts list says 66-70 keys yet, if all 5 keys in the thumb cluster were used, there would be 72. is there some design factor that prevents all 5 from being used?

**Comment by strayer** [comment]
Yes, the way the traces are set up the top keys would be wired together and both trigger the same key in QMK as far as I remember. [I did this without checking the traces and only realized this after finishing the build.](https://www.reddit.com/r/MechanicalKeyboards/comments/es8urx/it_may_not_be_as_pretty_as_others_but_i_finally/ff9t557/)

**Comment by jack-faller** [comment]
ok thx
