### ISSUE TITLE
Alternative for the MJTP1117 switch

### ISSUE THREAD

**Issue by MaKaNu** [omkbd/ErgoDash#42]
I have some trouble to find the switches. There are some reseller like mouser or digikey wit a decend price, but the transport costs are absurdly high for part in the cents area.

I also never saw this kind of switches around  europe.

Any Ideas for alternative switches, which are as best available around the world?

**Comment by strayer** [comment]
I also had trouble finding these *anywhere* with reasonable shipping. In the end I ordered them on AliExpress. Sadly the ones I ordered are not available anymore (https://de.aliexpress.com/item/32964192707.html), but it should be possible to find them there. I can send you some leftovers if you are interested, I should still have some of them – email me at strayer@olle-orks.org if you are interested.

**Comment by MaKaNu** [comment]
The AliExpress link helped a lot. For everyone else looking for the MJTP: "switch side press" will do the job. @Strayer thanks for offer.
