### ISSUE TITLE
Via cannot detect my ergodash

### ISSUE THREAD

**Issue by hailee0710** [omkbd/ErgoDash#48]
I flashed the firmware in this repo for both sides. Then I connect the keyboard into my computer and start Via. But it keeps searching for devices...
BTW, I see some posted that Ergodash is supported in via but cannot find the firmware in the official document [here](https://www.caniusevia.com/docs/supported_keyboards)

**Comment by chrishoage** [comment]
You need to sideload the JSON file found in the firmware zip

https://github.com/omkbd/ErgoDash/tree/master/Firmware

One you do this it will show up (note that you will need to do this every time you open via, I have not found a way to make the sideload json permanent. Same with Vial)
